# Configuration constants for the RAG Chatbot

# Cohere API settings
COHERE_EMBED_MODEL = "embed-english-v3.0"
COHERE_GENERATE_MODEL = "command-r-plus"
COHERE_EMBED_DIMENSION = 1024

# Chunking settings
CHUNK_SIZE_TOKENS = 400
CHUNK_OVERLAP_TOKENS = 100
MIN_CHUNK_SIZE = 50
MAX_CHUNK_SIZE = 1000

# Retrieval settings
TOP_K_RETRIEVAL = 7
DEFAULT_RERANK = True

# Performance settings
MAX_BOOK_PAGES = 1500
MAX_TOKENS_PER_BOOK = 1_000_000
RESPONSE_TIMEOUT_SECONDS = 60
MAX_RESPONSE_TIME_MS = 4000  # 4 seconds target

# Qdrant settings
QDRANT_TIMEOUT = 30
QDRANT_RETRIES = 3

# Database settings
NEON_CONNECTION_TIMEOUT = 30

# API settings
API_V1_STR = "/api/v1"
MAX_QUERY_LENGTH = 2000
MAX_SELECTED_TEXT_LENGTH = 5000

# Collection naming
MAIN_COLLECTION_PREFIX = "book_"
TEMP_COLLECTION_PREFIX = "temp_"
MAX_COLLECTION_NAME_LENGTH = 63  # Qdrant limit

# Environment variables
COHERE_API_KEY_ENV = "COHERE_API_KEY"
QDRANT_URL_ENV = "QDRANT_URL"
QDRANT_API_KEY_ENV = "QDRANT_API_KEY"
DATABASE_URL_ENV = "DATABASE_URL"
DEBUG_ENV = "DEBUG"
SECRET_KEY_ENV = "SECRET_KEY"

# Validation settings
MIN_TITLE_LENGTH = 1
MAX_TITLE_LENGTH = 200
MIN_AUTHOR_LENGTH = 1
MAX_AUTHOR_LENGTH = 100
MIN_QUESTION_LENGTH = 5
MAX_QUESTION_LENGTH = 2000
MIN_RESPONSE_LENGTH = 10
MAX_RESPONSE_LENGTH = 5000
MIN_SNIPPET_LENGTH = 10
MAX_SNIPPET_LENGTH = 500